var annotated_dup =
[
    [ "cse335", null, [
      [ "Cylinder", "classcse335_1_1_cylinder.html", "classcse335_1_1_cylinder" ],
      [ "Polygon", "classcse335_1_1_polygon.html", "classcse335_1_1_polygon" ]
    ] ],
    [ "Actor", "class_actor.html", "class_actor" ],
    [ "AnimChannel", "class_anim_channel.html", "class_anim_channel" ],
    [ "AnimChannelAngle", "class_anim_channel_angle.html", "class_anim_channel_angle" ],
    [ "AnimChannelPoint", "class_anim_channel_point.html", "class_anim_channel_point" ],
    [ "Box", "class_box.html", "class_box" ],
    [ "Cam", "class_cam.html", "class_cam" ],
    [ "CanadianExperienceApp", "class_canadian_experience_app.html", "class_canadian_experience_app" ],
    [ "Component", "class_component.html", "class_component" ],
    [ "Const", "class_const.html", "class_const" ],
    [ "Crank", "class_crank.html", "class_crank" ],
    [ "Drawable", "class_drawable.html", "class_drawable" ],
    [ "HaroldFactory", "class_harold_factory.html", "class_harold_factory" ],
    [ "HeadTop", "class_head_top.html", "class_head_top" ],
    [ "IActivate", "class_i_activate.html", "class_i_activate" ],
    [ "IMachineSystem", "class_i_machine_system.html", "class_i_machine_system" ],
    [ "ImageDrawable", "class_image_drawable.html", "class_image_drawable" ],
    [ "Machine", "class_machine.html", "class_machine" ],
    [ "MachineCFactory", "class_machine_c_factory.html", "class_machine_c_factory" ],
    [ "MachineDemoApp", "class_machine_demo_app.html", "class_machine_demo_app" ],
    [ "MachineDialog", "class_machine_dialog.html", "class_machine_dialog" ],
    [ "MachineDrawable", "class_machine_drawable.html", "class_machine_drawable" ],
    [ "MachineFactory2", "class_machine_factory2.html", "class_machine_factory2" ],
    [ "MachineStandin", "class_machine_standin.html", "class_machine_standin" ],
    [ "MachineSystem", "class_machine_system.html", "class_machine_system" ],
    [ "MachineSystemFactory", "class_machine_system_factory.html", "class_machine_system_factory" ],
    [ "MachineSystemIsolator", "class_machine_system_isolator.html", "class_machine_system_isolator" ],
    [ "MachineSystemStandin", "class_machine_system_standin.html", "class_machine_system_standin" ],
    [ "MainFrame", "class_main_frame.html", "class_main_frame" ],
    [ "Picture", "class_picture.html", "class_picture" ],
    [ "PictureFactory", "class_picture_factory.html", "class_picture_factory" ],
    [ "PictureObserver", "class_picture_observer.html", "class_picture_observer" ],
    [ "PolyDrawable", "class_poly_drawable.html", "class_poly_drawable" ],
    [ "Pulley", "class_pulley.html", "class_pulley" ],
    [ "RotatedBitmap", "class_rotated_bitmap.html", "class_rotated_bitmap" ],
    [ "RotationSink", "class_rotation_sink.html", "class_rotation_sink" ],
    [ "RotationSource", "class_rotation_source.html", "class_rotation_source" ],
    [ "Shaft", "class_shaft.html", "class_shaft" ],
    [ "Sparty", "class_sparty.html", "class_sparty" ],
    [ "SpartyFactory", "class_sparty_factory.html", "class_sparty_factory" ],
    [ "ThorHammerFactory", "class_thor_hammer_factory.html", "class_thor_hammer_factory" ],
    [ "Timeline", "class_timeline.html", "class_timeline" ],
    [ "TimelineDlg", "class_timeline_dlg.html", "class_timeline_dlg" ],
    [ "ViewEdit", "class_view_edit.html", "class_view_edit" ],
    [ "ViewTimeline", "class_view_timeline.html", "class_view_timeline" ]
];